### PR TITLE
Correctly handle properties in spanForElement, prepare for release

### PR DESCRIPTION
**Pull request by kevmoo**
Fixes https://github.com/dart-lang/source_gen/issues/379

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @samogot

**Comment by samogot** [comment]
Do I understand it correctly, that the problem was not in overriding, but it using getter instead of field?

**Comment by kevmoo** [comment]
> Do I understand it correctly, that the problem was not in overriding, but it using getter instead of field?

Yup. Properties are synthetic – they don't have a real location – you have to dig into either the getter or teh setter.

**Comment by samogot** [comment]
Will this code work properly if we have both getter and setter with the same name? Or it will always highlight getter even if the error is related to setter?

**Comment by kevmoo** [comment]
If the error is specific to the setter in a getter/setter pair, the calling code will need to be sure to pass in the setter specifically.

If it's vague, you're right, the getter is picked.

**Pull request merged**
