### PR TITLE
cleanup: move to mono_repo

### PR DESCRIPTION
**Pull request by kevmoo**
Will land as a single commit once https://github.com/dart-lang/source_gen/pull/336 lands

### CODE REVIEW

**Comment by natebosch** [comment]
What is the root level `README` link accomplishing for us here?

**Comment by kevmoo** [comment]
keeping us from having to duplicate content? Or keep something up-to-date. 🤷

**Comment by natebosch** [comment]
Oh interesting, this does make the landing page on github nicer. It doesn't work for the `/blob` URLs which is what I had been looking at.

**Comment by natebosch** [comment]
I think it does probably make sense for us to link the README by default when there is a clear "main" package. I'll do that in `test`. https://github.com/dart-lang/test/pull/1477

**Pull request merged**
