### PR TITLE
fix #104 generate valid lists in strong mode

### LINKED ISSUE #104: JsonSerializable: generate valid lists in strong mode
Currently, lists will generate a constructor like this:

```dart
// source
class User extends Object with _$UserSerializerMixin {
  List<int> tags;
  User(this.tags);
  factory User.fromJson(Map json) => _$UserFromJson(json);
}

// generated
User _$UserFromJson(Map json) => new User(
(json['tags'] as List)?.map((v0) => v0)?.toList());
```

Which generates the following strong-mode error:

```
WARNING: Unsafe implicit cast from 'List<dynamic>' to 'List<int>'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. ([revolution] lib/model.g.dart:725)
```

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by jakemac53** [comment]
By default strong mode would insert implicit casts for these afaik, do you have that disabled?

**Comment by a14n** [comment]
See #104

**Comment by jakemac53** [comment]
Ah, nvm I see in the latest sdk that the `List<int>` case is broken.

**Comment by a14n** [comment]
btw should the generated code be `strong-mode: true` error-free or `strong-mode: implicit-casts: false` error-free ? My PR puts the generated code between the two setup :)

**Pull request merged**
