### PR TITLE
update the pubspec 'repository' field

### PR DESCRIPTION
**Pull request by devoncarew**
- update the pubspec 'repository' field

### CODE REVIEW

**Review by natebosch — APPROVED** [review]
If this is worth publishing by itself, it's OK for it to go out without rolling the package internally since these files have no impact in bazel. You could skip the `-dev` if you plan to publish.

**Comment by devoncarew** [comment]
> If this is worth publishing by itself, it's OK for it to go out without rolling the package internally since these files have no impact in bazel. You could skip the `-dev` if you plan to publish.

Will do!

It looks like the CI is unhappy w/ some new analyzer deprecations from `5.2.0`. I'll hold off on landing this until I've had a chance to look into the deprecations.

**Comment by devoncarew** [comment]
It looks like in order to make the CI happy, we either need to address the deprecations (just referencing the non-deprecated members) and set analyzer `5.2.0` - the current version - as our min. required version, or adjust the analysis options to ignore deprecations.

**Comment by natebosch** [comment]
https://github.com/dart-lang/source_gen/pull/627 bumps the analyzer dep and migrates from deprecated APIs.

**Comment by devoncarew** [comment]
I'll update this once the other PR lands.

**Pull request merged**
