### PR TITLE
Only add dart format width comment on format

### LINKED ISSUE #724: Add "// dart format width=80" comment in generated code
After many years of users asking for it, we are adding support to the formatter for project-wide page width configuration using a surrounding `analysis_options.yaml` file (https://github.com/dart-lang/sdk/issues/56863). However, tools like source_gen don't necessarily have access to (or want to access) IO or know where generated code will end up on disk.

To avoid breaking CI by having the code get generated and formatted at one width and then get formatted to a different width when the user runs `dart format`, we also added support for putting a marker comment in a file to specify an explicit width, like:

```dart
// dart format width=80
```

When this comment is present at the top of the file (before any code, but can be after other comments), then that comment will take precedence and the file will reliably be formatted at that width regardless of any surrounding configuration. So if code generators insert that comment at the top of the code they generate, they don't have to worry about reading the user's configuration.

This issue is requesting that source_gen be updated to add that comment to the code it generates. Since it's just a comment, it's safe to add this at any time. Let me know if you have any questions/feedback and I'll do my best.

### PR DESCRIPTION
**Pull request by natebosch**
Closes #724

A use case with a custom `formatCode` callback can reasonably use a
different line width than the default, so only add the width comment
when this package is responsible for performing a format.

Uses with a custom header will no longer slot the width comment in
following the header.

Some outputs will no longer have the comment. This is not breaking since
there has been no published since the comment was introduced.

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]

**Comment by kevmoo** [comment]
So the idea here is that we don't have a good way to extract the style info from analysis_options, so we're just going to hard-wire?

**Comment by natebosch** [comment]
> So the idea here is that we don't have a good way to extract the style info from analysis_options, so we're just going to hard-wire?

Yes. It is not guaranteed that the configuration is in a file that we make readable during builds.

**Comment by marvin-kolja** [comment]
@natebosch, may I ask why the comment was added as a first line? This conflicts with GitHub Linguist to recognize the file as generated (https://github.com/github-linguist/linguist/blob/main/lib/linguist/generated.rb#L737). I was about to fix a related issue in Freezed (https://github.com/rrousselGit/freezed/issues/1261) when I came across this.

**Comment by natebosch** [comment]
I'm not sure what it would take to change the ecosystem to allow the comment on the second line. If we need to reorder the lines we either need a breaking change to the signature of the callback (we'd need to pass the header and body separately to put the line width comment between them) or we can do something hacky and hardcode support for the generate content line specifically. I'd lean towards doing the latter so I'll open a PR with that approach, but I haven't fully thought it through and I can't roll out the change. @kevmoo @jakemac53 if you think this is urgent you may want to run with https://github.com/dart-lang/source_gen/pull/760

**Comment by marvin-kolja** [comment]
Thanks for the quick response.

_For now, I've also opened a request to improve how GitHub Linguist recognizes generated files by looking at the first 3 lines https://github.com/github-linguist/linguist/pull/7448._

Like that second idea, I will have a look.

**Pull request merged**
