### PR TITLE
Use aliasElement over element for DartType

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Comment by natebosch** [comment]
@scheglov see the second commit here - I had to add back a check for `GenericFunctionTypeElement` to get the tests to pass. Does this look correct to you?

**Comment by scheglov** [comment]
No, this does not look right - we should be able to use just `aliasElement`.

**Comment by natebosch** [comment]
> No, this does not look right - we should be able to use just `aliasElement`.

Without the extra code:

```
01:11 +167 -2: test/utils_test.dart: should return the name of a function type [E]                                                                                                                     
  UnimplementedError: (FunctionTypeImpl) dynamic Function()
  package:source_gen/src/utils.dart 34:3  typeNameOf
  test/utils_test.dart 41:12              main.<fn>
```

The test in question uses the legacy style typedef.

https://github.com/dart-lang/source_gen/blob/bacd2edcd710149e2282d86ed65594af9f39b4a3/source_gen/test/utils_test.dart#L25

**Comment by scheglov** [comment]
Yes, I see that it does not work.
Support for `aliasElement` was added only recently, and the only version that supports it is `analyzer 0.42.nullsafety.0`.

**Review by scheglov — APPROVED** [review]

**Review by jakemac53 — APPROVED** [review]

**Pull request merged**
