### PR TITLE
Migrate source_gen to null-safety

### LINKED ISSUE #493: Add support for nullsafety
I am upgrading my package (Kiwi) https://github.com/vanlooverenkoen/kiwi/issues/51

But it seems that source_gen is not yet migrated to support nullsafety. Is there a timeline on when this could be added?

### PR DESCRIPTION
**Pull request by simolus3**
Migrates `source_gen`, tests and the example.

Still blocked by

- ~~`build_config`, `build_runner_core` and `build_runner` not being released yet~~ :heavy_check_mark: 
- https://github.com/dart-lang/dart_style/pull/1000 (and that being published)

Closes #493

### CODE REVIEW

**Comment by jakemac53** [comment]
It would be good to have a version that allows `build` version 2.0.0 first (as well as 1.x), and then do this migration. That should allow people to migrate a bit more incrementally.

**Comment by simolus3** [comment]
Agreed, should I open another PR for that or is someone working on that already?

**Comment by jakemac53** [comment]
> Agreed, should I open another PR for that or is someone working on that already?

Nobody is actively working on it right now afaik, either way :). https://github.com/dart-lang/source_gen/issues/516 is the issue which nobody has grabbed yet.

**Comment by simolus3** [comment]
The only remaining dependency override is in `example_usage`, so this should be ready for review now :)

**Comment by kevmoo** [comment]
I think we duplicated work - https://github.com/dart-lang/source_gen/pull/520

**Comment by simolus3** [comment]
I'm ok with closing this PR then, but this isn't great. I spent a non-trivial amount of time on this and announced that I was going to work on this in the tracking issue quite some time ago. Very respectfully, I don't see how _I_ duplicated work here.
Whatever, I'm glad we can get this package migrated.

**Comment by kevmoo** [comment]
> I'm ok with closing this PR then, but this isn't great. I spent a non-trivial amount of time on this and announced that I was going to work on this in the tracking issue quite some time ago. Very respectfully, I don't see how _I_ duplicated work here.
> Whatever, I'm glad we can get this package migrated.

You're welcome to be upset here. I'm sorry. There are some non-trivial code paths I wanted to double check.

...and honestly I didn't see your PR before I started.

I'd love your eyes on my review, if you're willing.

Regardless, my sincere apologies. Thanks for your help here!

**Pull request closed without merging**
