### PR TITLE
Upgrade to build 0.9.0

### PR DESCRIPTION
**Pull request by natebosch**
- Replace declareOutputs with buildExtensions
- Upgrade build related dependencies

### CODE REVIEW

**Comment by kevmoo** [comment]
FYI, @natebosch – might could have updated the min SDK constraint to `1.21.1` as well...

**Comment by natebosch** [comment]
Min SDK constraint was already 1.21.1

**Comment by kevmoo** [comment]
Er 1.22.1

From mobile. Sorry for brevity and/or spelling.

**Comment by natebosch** [comment]
Since the SDK constraint is tightened in package:build rather than by usage here I don't think it makes sense to update this constraint - we let pub figure that out for us. IMO it doesn't make sense to transitively search a package's dependencies to find the SDK constraint but to specify it based on language usage within this package.

**Comment by kevmoo** [comment]
>  IMO it doesn't make sense to transitively search a package's dependencies to find the SDK constraint but to specify it based on language usage within this package.

For me it's about support. If we can't test version X, we shouldn't claim to support it.

**Pull request merged**
