### PR TITLE
Use latest pkg/build

### PR DESCRIPTION
**Pull request by kevmoo**
And other cleanup

### CODE REVIEW

**Comment by jakemac53** [comment]
LGTM, but I did just realize we also need to update the README/examples

**Comment by kevmoo** [comment]
@jakemac53 working on REAME now.

What needs fixing in examples?

**Comment by jakemac53** [comment]
Oh nvm, it looks like I did update the examples (the one linked in the readme at least)

**Comment by kevmoo** [comment]
@jakemac53 See latest commit for some tweaks to readme – ditching references to Dart editor, pointing to pkg/build – etc

**Comment by jakemac53** [comment]
lgtm!

**Pull request merged**
