### PR TITLE
Use build pkg

### PR DESCRIPTION
**Pull request by jakemac53**

### CODE REVIEW

**Comment by kevmoo** [comment]
@jakemac53 I pushed another commit w/ a couple of tweaks. Review. Rebase. Land it!

**Comment by jakemac53** [comment]
Dev bots are failing because test didn't support the dev sdk until very recently. Going to wait a bit and try re-running to make sure everything is ok.

**Comment by jakemac53** [comment]
Actually it looks like scheduled_test needs to be updated to support the latest test

**Comment by jakemac53** [comment]
Ok, I actually just removed scheduled_test it entirely as a dep since it was no longer being used. I also moved `io.dart` under the test folder since that was no longer used by the main libs.

**Pull request merged**
