### PR TITLE
Including extensions on allElements

### LINKED ISSUE #468: [LibraryReader] allElements does not include extensions
https://github.com/dart-lang/source_gen/blob/4fb8a656b8108e7ff45b5d1f5048ac6851522854/source_gen/lib/src/library.dart#L37-L59

Since `allElements` does not load extensions if I use `annotatedWith` to get extensions with some annotation it will not return them.

### PR DESCRIPTION
**Pull request by AlbertoMonteiro**
Fixes #468

### CODE REVIEW

**Comment by natebosch** [comment]
Looks good! Can you add an entry to the CHANGELOG?

**Comment by kevmoo** [comment]
@natebosch – think we need a test here? Also bump the version?

**Comment by natebosch** [comment]
> think we need a test here?

I can take a look at that in a followup.

> Also bump the version?

Version is already bumped appropriately. We are at a `-dev`.

**Comment by AlbertoMonteiro** [comment]
@natebosch I've changed changelog, let me know if need something else 😁

**Comment by natebosch** [comment]
Thanks!

There will be some lag before we can get this published. I've still been fighting some internal tests following #455

**Comment by AlbertoMonteiro** [comment]
Tyvm @natebosch

**Pull request merged**
