### PR TITLE
Prepare a 0.8.3 release

### PR DESCRIPTION
**Pull request by kevmoo**
Since 0.9.0 is blocked by `pkg:build_` issues...

### CODE REVIEW

**Comment by kevmoo** [comment]
This unblocks a long-standing feature request in json_serializable

**Comment by natebosch** [comment]
why do we need this?

**Comment by kevmoo** [comment]
> why do we need this?

"This unblocks a long-standing feature request in json_serializable" – namely annotating enum values. Now unblocked by pkg:analyzer release. Figured this was better than pushing you all to fix the pending pkg:build_ issue

**Comment by kevmoo** [comment]
To be more clear for @natebosch and @jakemac53 – currently (at master) we are set to be 0.9.0-dev. This includes the SharedPartBuilder crazy that we **cannot** release until https://github.com/dart-lang/build/issues/1578 is fixed

This pulls the bits out of master that we could still release as 0.8.x – namely letting generateForAnnotation return Iterable/Stream.

**Pull request merged**
