### PR TITLE
Add GeneratorForAnnotation.generateForAnnotatedElementStream

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
towards https://github.com/dart-lang/source_gen/issues/403

**Comment by natebosch** [comment]
Why is this useful? `generateForAnnotatedElement` can return a `Stream<String>`.

**Comment by kevmoo** [comment]
> Why is this useful? `generateForAnnotatedElement` can return a `Stream<String>`.

This normalizes the return value (which can be many things) to `Stream<String>` – it's mostly for testing generators.

**Comment by natebosch** [comment]
>  it's mostly for testing generators.

I'm not in favor of increasing the surface area and cognitive load for implementors to do that - if we do decide to move forward with a test package we can copy/paste the normalize function into that package.

**Comment by kevmoo** [comment]
> I'm not in favor of increasing the surface area and cognitive load for implementors to do that - if we do decide to move forward with a test package we can copy/paste the normalize function into that package.

ack

**Pull request closed without merging**
