### PR TITLE
Make PartBuilder also output language version.

### PR DESCRIPTION
**Pull request by davidmorgan**

### CODE REVIEW

**Comment by davidmorgan** [comment]
Thanks, PTAL.

**Comment by davidmorgan** [comment]
Thanks :)

Can I help with pulling into google3? It's not urgent though--I guess it'll be mid/late next week before all the other pieces are in place for me to need this.

**Comment by kevmoo** [comment]
Please! I don't get on my cloud top often...

**Comment by kevmoo** [comment]
@davidmorgan – do you want me to publish externally?

**Pull request merged**
