### PR TITLE
Revive to the object's `variableElement` if available

### PR DESCRIPTION
**Pull request by mattrberry**
Variables have been tracked on DartObject since https://dart.googlesource.com/sdk/+/54b7f4b72a1701f8f9a0334c94ce6f59732bd261. This change uses the variable in the reviver if it exists. I believe the existing tests in https://github.com/dart-lang/source_gen/blob/master/source_gen/test/constants_test.dart already cover this, but lmk if you'd like any additional tests

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by kevmoo** [comment]
I mean, if this changes the behavior, we should have a test that shows the behavior change/improvement...right?

**Comment by mattrberry** [comment]
This is really just a fast-path that avoids iterating all members in the library rather than a change in behavior.. That said, `revive` doesn't support extension types yet, so this technically does change behavior in that it adds support for extension types assigned to variables that would be otherwise un-revivable. It's not really a regression test for this feature, but it's something.

**Comment by kevmoo** [comment]
Please add a changelog entry!

**Review by kevmoo — APPROVED** [review]

**Comment by jakemac53** [comment]
Fwiw the issue seems to be that imports don't get added for these variables in generated mockito code. That might just be a mockito bug or something I am not sure.

**Comment by mattrberry** [comment]
I also just looked at one case and it seems like the source_gen Revivable is correct, which would align with your thought that mockito just isn't emitting the import. I haven't worked much with mockito, but I can take a look if you aren't already

**Comment by jakemac53** [comment]
> but I can take a look if you aren't already

If you can that would be great, I only looked enough to understand mockito was the problem

**Comment by mattrberry** [comment]
Mockito [assumes](https://github.com/dart-lang/mockito/blob/2259e105b335b7a4b3a4df313ce4099e8a92a959/lib/src/builder.dart#L1874) that the import uri is where the object's type is defined, which isn't always true. This seems like a bug in mockito.

e.g.

```dart
# foo.dart
class Foo {
  static final bar = Bar();
}
# bar.dart
class Bar {}
```

With this change, we now create a `Revivable` for `Foo.bar`, and mockito reads the import for that as `bar.dart` rather than `foo.dart`.

**Pull request merged**
