### PR TITLE
Fix tests on travis for deprecated API

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
HRM....requires bumping min analyzer to 0.39.0...not sure if we're ready for that...

**Comment by natebosch** [comment]
`build_resolvers` is already at `0.39.0`. I'm fine bumping here as well.

**Comment by kevmoo** [comment]
> `build_resolvers` is already at `0.39.0`. I'm fine bumping here as well.

Wha?

**Comment by kevmoo** [comment]
Otherwise LGTY @natebosch @jakemac53 ?

**Comment by natebosch** [comment]
I don't think it is worth submitting this unless the red travis is blocking something else. We should instead upgrade the version of analyzer.

**Comment by kevmoo** [comment]
> I don't think it is worth submitting this unless the red travis is blocking something else. We should instead upgrade the version of analyzer.

0.40.0 is coming soon. I'd rather get things green (so we catch any other regressions) and wait for that

**Comment by natebosch** [comment]
https://github.com/dart-lang/source_gen/pull/437

**Pull request closed without merging**
