### PR TITLE
Add support for allowSyntaxErrors flag

### LINKED ISSUE #485: Support `allowSyntaxErrors` flag
[This PR](https://github.com/dart-lang/build/pull/2797), from the `build` package, added code that throws when resolving libraries with syntax errors. It also added the flag `allowSyntaxErrors` to `BuildStep.resolver.libraryFor()` to opt-out of that behavior.

However, when using source_gen, I cannot find a way to opt-out of that behavior.

The method `_Builder.build()` in builder.dart in the source_gen package is using `buildStep.inputLibrary` which throws when resolving a library with syntax errors.

The source_gen `*Builder` classes could be modified to accept a flag to allow syntax errors. Their constructors could take a named parameter for the flag which could then be used inside the `_Builder.build()` method to call `buildStep.resolver.libraryFor(...)` instead of `buildStep.inputLibrary`.

I could work on a PR for that change if the approach makes sense.

### PR DESCRIPTION
**Pull request by fertrig**
Fixes #485

### CODE REVIEW

**Comment by fertrig** [comment]
@googlebot I signed it!

**Comment by fertrig** [comment]
@jakemac53 I am getting dependency issues. I think this is what's happening:

- `package:build_runner` is a dev_dependency of source_gen. 
- The flag `allowSyntaxErrors` is part of `package:build` version 1.4.0. 
- `pub get` resolves `package:build` to version 1.5.0,
- To use `package:build` version 1.5.0, `package:build_runner` would need version 1.10.3.
- `package:build_runner` version 1.10.3 requires `sdk: ">=2.10.0-93.0.dev <3.0.0"`

Is it ok if I bump the minimum sdk version to 2.10.x? I think that will require changes in multiple files (.travis.yml, mono_pkg.yaml and pubspec.yaml).

**Review by jakemac53 — COMMENTED** [review]
> Is it ok if I bump the minimum sdk version to 2.10.x? I think that will require changes in multiple files (.travis.yml, mono_pkg.yaml and pubspec.yaml).

Yes, go ahead and bump that to `2.10.0`. You will also need to edit the `mono_pkg.yaml` files and replace the occurrences of `2.7.0` with `2.10.0` and then run `pub global activate mono_repo` and `pub global run mono_repo travis`, and commit the result to update our travis jobs.

This looks great otherwise, just a few minor style nits to retain trailing commas where previously used (makes future diffs a little bit nicer). Feel free to either manually apply those changes or commit the suggestions, whichever is easier.

**Comment by fertrig** [comment]
@jakemac53 please let me know if this PR looks good. Thanks!

**Review by jakemac53 — APPROVED** [review]
@kevmoo did you want to take a look as well?

**Comment by fertrig** [comment]
@jakemac53 @kevmoo - will it be possible to publish this new version to pub.dev?

**Comment by jakemac53** [comment]
Published, thanks!

**Pull request merged**
