### PR TITLE
add test for enum assignability

### PR DESCRIPTION
**Pull request by jakemac53**
Related to https://github.com/dart-lang/source_gen/issues/638

### CODE REVIEW

**Comment by jakemac53** [comment]
Interesting this is failing on Windows, but not Linux?

**Comment by jakemac53** [comment]
And only the runtime version

**Comment by kevmoo** [comment]
> And only the runtime version

👀  VERY!

**Comment by jakemac53** [comment]
The runtime version does use mirrors, but it is passing on linux and not on windows so that part is really confusing

**Comment by jakemac53** [comment]
Oh, https://github.com/dart-lang/source_gen/issues/573 :)

**Comment by kevmoo** [comment]
> Oh, #573 :)

🤣 🤣 🤣

**Comment by jakemac53** [comment]
@kevmoo I can has lgtm?

**Review by kevmoo — APPROVED** [review]

**Comment by jakemac53** [comment]
@kevmoo I don't have merge powers here it looks like so you will need to

**Pull request merged**
