### PR TITLE
Add sortedFields and isEnum utils

### PR DESCRIPTION
**Pull request by kevmoo**
And remove now unneeded (and not public anyway) `friendlyNameForElement`

### CODE REVIEW

**Comment by kevmoo** [comment]
I've needed `sortedFields` twice

https://github.com/kevmoo/build_cli/blob/master/build_cli/lib/src/to_share.dart#L144
https://github.com/dart-lang/json_serializable/blob/master/json_serializable/lib/src/utils.dart#L144

So there is a need.

I'm trying to centralize this non-trivial logic to help others – and hopefully solve it one place.

**Comment by matanlurey** [comment]
I understand. I still don't think we should use any more private implementation details given that the analyzer team is going to be (and is) working very hard to make a new stable API on top of the CFE.

**Comment by natebosch** [comment]
`s/needed/wanted`

I understand that it's _nice_ to have generated code use the same ordering as the source - what would be _broken_ without it?

**Comment by matanlurey** [comment]
We've already put our feet down and blocked many changes here and in angular and elsewhere.

Neither of those two packages are P1s for our customers, but keeping `source_gen` running is. Feel free to schedule a VC if you'd like to discuss these concerns more in person.

**Pull request closed without merging**
